Created API Based Web Tech Jobs Application
Shaheryar0054/react-capstone pull request #1
Opened 2023-05-31 16:56 UTC by Shaheryar0054

- I choose Jobs API to display tech jobs
- Fetched data from the Jobs API
- Added Home page 
- When the page loads, the web app shows the list of categories that could be filtered out by some parameter, for example by the 
Jobs title.
- Along with the Title of the job, It shows the total number of jobs Available.
- When the user clicks on the job title, the application navigates to the details page.
- Added Details Page
- On the detail page it shows details about the job e.g salary etc.
- Added test cases for the components.

2023-05-31 19:20 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Shaheryar0054👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- All tests are passed. ✔️
- Highly organized code. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 19:20 UTC, thecodechaser commented on src/components/JobList.js
> +  const totalTechJobsCount = jobs.length;
- [ ] You did really a great job on this project but you missed a major requirement. Please add a feature on the home page to filter items(jobs). (You should include a search feature on the page).
![image](https://user-images.githubusercontent.com/83803414/193900059-ae0b963d-7671-4e1c-910c-bc3ad366aaa2.png)

2023-05-31 19:20 UTC, thecodechaser commented on README.md
> +
- [ ] Please make sure to give appropriate credit to the author in the README for the original design idea to [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio) as requested in the project requirements.

2023-06-01 12:08 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Shaheryar0054 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
- No linter errors ✔️ 
- Search functionality added ✔️ 
- App works as expected ✔️ 
- All tests passing ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 12:08 UTC, nahnahdev commented on README.md
> +- Hat tip to anyone whose code was used.
- [ ] Great job including the search functionality as the previous reviewer mentioned on the homepage 😉 It works as expected. However, I noticed that you failed to give appropriate credit in your README for the original design idea to [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio) as requested in the project requirements and also as mentioned by the previous reviewer. So kindly implement that 💯

2023-06-01 12:08 UTC, nahnahdev commented on src/components/JobList.js
> +  // eslint-disable-next-line max-len
- [ ] I recommend avoiding the use of `eslint` disable commands in your projects, as these errors and warnings are typically helpful for identifying areas where you can improve your code. By resolving these issues, you can write more clean and readable code that adheres to industry standards, which can make it easier to maintain your codebase over time. :100:

2023-06-01 12:35 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Shaheryar0054 ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] You may always write your commit messages in an imperative tense something like `Add Home Button` instead of `Added Home Button`.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 12:36 UTC, merged